name: Release PHAR

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Install dependencies (no dev)
        run: composer install --no-dev --prefer-dist --no-interaction

      - name: Build PHAR
        run: php -d phar.readonly=0 scripts/build-phar.php

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: malcode-scan-phar
          path: build/malcode-scan.phar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/malcode-scan.phar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
